"use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { ResetProvider } from "@/context/ResetContext";

export const metadata: Metadata = {
  title: "test ambisius coding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ResetProvider>
        <body className="px-6 pt-5">
          <div className="space-y-1">
            <h1 className="text-3xl font-semibold">
              [Test Mhd Raiza Farhan] Sistem Restoran
            </h1>
            <p className="text-[#65758C] text-sm">
              Ambisus Coding Challange #2309116H
            </p>
          </div>
          <Navbar />

          {children}
        </body>
      </ResetProvider>
    </html>
  );
}
